---
title: "Titles and Labels"
webr:
  packages: ['dplyr', 'readr', 'ggplot2', 'tidyr', 'stringr']
---

## Communicating better with visualisations

Adding titles, labels and annotations greatly increases the readability of your charts. This is dependent on context, too. It's not usually required or recommended to add a chart title in a visualisation in an academic book or article, but a chart in a report, blog post, or piece of data journalism usually benefits from a title.

A good principle is to try to make your chart stand on its own without further explanation, as far as possible. Even if your visualisation is embedded within a report, readers often skip to the chart first without looking at the underlying context. And charts often get separated from their context if they are shared on social media, for example.

For a chart to stand alone, consider adding the following:

-   An eye-catching title, which explains the 'headline' of your chart.

-   A subtitle, with further explanation

-   A caption, which gives other relevant information, particularly the data source, or any necessary caveats to the data.

-   Relevant labels for the axes and legends

-   Annotations pointing out key findings.

Be a little bit careful with this last point: it depends on the context. Dry, scientific publications probably don't expect 'editorialising' through annotations or labels, but in the context of a blog post or newspaper article, they can be useful.

## Adding labels with the labs() function

There are many ways to add labels to your charts. The simplest is by adding `labs()` as a layer to your ggplot chart, using `+`. `labs()` allows you to specify titles and captions for your charts, **as well as the label for the axis or legend of any of your aesthetics**.

Within the parentheses of the `labs()` layer, you can specify the arguments `title =`, `subtitle =`, `caption =`, as well as any aesthetic in your plot, for example, `x =`, `y =`, `fill =` and so forth.

Make sure to include the text of your label within quotation marks. If you would like to spread your title across multiple lines, you can specify a line break by adding the code `\n` within your title.

```{webr-r}
#| context: setup
library(readr)
library(ggplot2)
library(dplyr)
library(tidyr)
library(stringr)

url1 <- "https://raw.githubusercontent.com/yann-ryan/infovis_data/main/nobel/laureates_df.csv"
download.file(url1, "laureates_df.csv")
laureates_df <- read_csv('laureates_df.csv')

url2 <- "https://raw.githubusercontent.com/yann-ryan/infovis_data/main/nobel/prize_df.csv"
download.file(url2, "prize_df.csv")
prize_df <- read_csv('prize_df.csv')

nobel_df <- laureates_df |>
  left_join(prize_df, by = 'prize_id') |>
  mutate(birth_year = as.numeric(str_sub(birth_date, 1, 4)),
         age_at_award = award_year - birth_year)

```

As an example, let's reuse a dataset from the colour chapter. What aesthetics are specified in this chart?

```{webr-r}

df <- nobel_df |>
  group_by(category) |>
  summarise(n = n(),
            pct_female = mean(gender == 'female', na.rm = TRUE) * 100,
            avg_age = mean(age_at_award, na.rm = TRUE))

```

```{webr-r}

df |>
  ggplot(aes(x = avg_age, y = pct_female, size = n, color = category))  +
  geom_point()

```

### Titles, subtitles, and captions.

To add a `title`, `subtitle`, or `caption`, add within the `labs()` parenthesis, followed by the text you wish to add in quotation marks.

```{webr-r}

df |>
  ggplot(aes(x = avg_age, y = pct_female, size = n, color = category))  +
  geom_point() +
  labs(title = "Age and Gender\nat the Nobel Prize")

```

**Try it yourself:** add a subtitle noting the time period covered (1901-2024) and a caption citing the source of the data: the Nobel Prize API, https://www.nobelprize.org/organization/developer-zone-2/.

```{webr-r}

```

::: callout-tip
You can force ggplot to create a new line by adding `\n` to your text, for example `"Age and Gender\nat the Nobel Prize"`. This is useful if you have longer titles which would otherwise overrun the width of the plot, because ggplot does not resize the text automatically.
:::

### Labelling aesthetics

To recap the last chapter, when you specify an aesthetic, such as `x`/`y`, `color` and so forth, ggplot2 automatically creates a scale, which is visualised by either an axis or a legend. By default, ggplot takes the axis and legend labels directly from the column names. `labs()` allows you to override these labels. Simply specify the aesthetic and the new label:

```{webr-r}

df |>
  ggplot(aes(x = avg_age, y = pct_female, size = n, color = category))  +
  geom_point() +
  labs(title = "Age and Gender\nat the Nobel Prize",
       x = "Average Age at Award")

```

::: callout-tip
If you are likely to have a lot of arguments within a function, like here, it can make it more readable to put each on a new line, after the comma.
:::

**Try it yourself:** Copy the plot above and change the y axis to "% of Laureates Who Were Women", and the size legend to "Number of Laureates". Put part of the size legend label on a new line.

```{webr-r}

```

You can change the label for any aesthetic you specify in your chart. You can also remove a label completely by setting it to NULL, e.g.

```{webr-r}

df |>
  ggplot(aes(x = avg_age, y = pct_female, size = n, color = category))  +
  geom_point() +
  labs(title = "Age and Gender\nat the Nobel Prize",
       x = NULL)

```

This can be a good idea in some cases where the label is obvious, for example when it displays the year.

## Geom text

There are a few ways you can add labels to your charts themselves. One is to add text as an aesthetic using geom_text(). Another is to add annotations directly using another layer: annotate().

Starting with the first, using geom_text. Geom_text will add text to your chart based on x and y positions, plus an extra label argument specifying which column it should take labels from.

```{webr-r}
df |>
  ggplot(aes(x = avg_age, y = pct_female, size = n, color = category))  +
  geom_point() +
  geom_text(aes(label = category), size = 3) +
  labs(title = "Age and Gender\nat the Nobel Prize",
       x = NULL)
```

With only six categories this is still fairly readable, but in cases with more categories, plotting all the names will result in an unreadable chart. One way to plot a small number of chosen labels is to create a new filtered dataset, and add this as the `data =` argument to `geom_text()`.

```{webr-r}

df_text = df %>% filter(category %in% c('Peace', 'Physics'))

df |>
  ggplot(aes(x = avg_age, y = pct_female, size = n, color = category))  +
  geom_point() +
  geom_text(data = df_text, aes(label = category), size = 4) +
  labs(title = "Age and Gender\nat the Nobel Prize",
       x = NULL)

```

### Working with text.

Sometimes, we'll want to make changes to the labels using the data. We can do this using stringr and paste functions. Within the paste function, enter each column separated by a comma. You can add text within quotation marks, also separated by commas.

The function `paste()` allows us to paste together text from several columns. For example, we could make a new column containing the category and the percentage of women:

```{webr-r}

df_text = df |>
  filter(category %in% c('Peace', 'Literature')) |>
  mutate(category_pct = paste(category, " (", round(pct_female), "%)", sep = ''))

df |>
  ggplot(aes(x = avg_age, y = pct_female, size = n, color = category))  +
  geom_point() +
  geom_text(data = df_text, aes(label = category_pct), size = 4, color = 'black') +
  labs(title = "Age and Gender\nat the Nobel Prize",
       x = NULL)

```

Question: Can you fix the chart so the writing is not covered? (think back to the use of scales).

```{webr-r}

```

::: {.callout-tip}
It can also be useful to make changes to the text in other ways. the `stringr` package has some functions which will allow you to make changes to the formatting of the text before you plot it.

-   str_trunc will shorten the text to a fixed length, useful for overly long labels. Set the number of characters with the `width =` argument.
-   `str_to_lower`, `str_to_upper`, and `str_to_title` will change the text to lower case, upper case, and title case (where the first letter of each word is upper case) respectively.
-   `str_extract` and `str_remove` allow you to extract or remove parts of a text column based on regular expressions.
:::

**Try it yourself:** copy the code for the previous chart. Label all six categories, make them all upper case, and truncate the text to at most 12 letters (some category names, like "Physiology or Medicine", are quite long!). Paste together the category name and the average age (rounded), with a comma in between.

```{webr-r}


```
