---
title: "Annotations and Highlights"
webr:
  packages: ['dplyr', 'readr', 'ggplot2', 'tidyr', 'stringr']
---

```{webr-r}
#| context: setup
library(readr)
library(ggplot2)
library(dplyr)
library(tidyr)
library(stringr)

url1 <- "https://raw.githubusercontent.com/yann-ryan/infovis_data/main/nobel/laureates_df.csv"
download.file(url1, "laureates_df.csv")
laureates_df <- read_csv('laureates_df.csv')

url2 <- "https://raw.githubusercontent.com/yann-ryan/infovis_data/main/nobel/prize_df.csv"
download.file(url2, "prize_df.csv")
prize_df <- read_csv('prize_df.csv')

nobel_df <- laureates_df |>
  left_join(prize_df, by = 'prize_id') |>
  mutate(birth_year = as.numeric(str_sub(birth_date, 1, 4)),
         age_at_award = award_year - birth_year)

df <- nobel_df |>
  group_by(category) |>
  summarise(n = n(),
            pct_female = mean(gender == 'female', na.rm = TRUE) * 100,
            avg_age = mean(age_at_award, na.rm = TRUE))

nobel_by_year <- tibble(award_year = 1901:2024) |>
  left_join(nobel_df |> count(award_year), by = 'award_year') |>
  mutate(n = replace_na(n, 0))

```

## Drawing readers to the data in your chart

The chart above might be a faithful representation of the data, but it doesn't really tell a story.

To do this, we'll draw viewers' attention to particular parts of the data using a few techniques. These use a cognitive process known as 'pre-attentive processing', meaning we are drawn to certain visual elements before others. Highlighting using colour and annotations are ways to use this to our advantage.

## Adding annotations using annotate()

Another way to add annotations to your text is using the layer `annotate()`. annotate allows you to add geoms directly to your plot, but instead of taking positions from your data, you specify them directly.

For annotate, you specify the name of the geom (a short version, so geom_rect becomes simply rect). Then you will directly specify the position coordinates and any other aesthetics. The most useful geom types here are the graphical 'primitives', such as `rect`, `polygon`, and `segment`, as well as `text`.

### Text

You can use annotate() to manually add informative labels to your charts.

It's usually useful to have an arrow along with text, pointing to something in the visualisation. Let's walk through doing this using the following chart, which charts the average age at award and the percentage of female laureates, for each prize category:

```{webr-r}
df |>
  ggplot(aes(x = avg_age, y = pct_female, size = n))  +
  geom_point() +
  labs(title = "Age and Gender\nat the Nobel Prize") + scale_size_area()
```

#### Adding a text annotation

We want to add the text Peace and an arrow pointing to the relevant point.

First we'll put a text annotation somewhere in the large empty space of the chart. Peace is towards the top-left of the plot (the highest share of women, at a fairly average age), so a spot up and to the left of it would be a good place to put the text.

```{webr-r}
df |>
  ggplot(aes(x = avg_age, y = pct_female, size = n, color = category))  +
  geom_point() +
  labs(title = "Age and Gender\nat the Nobel Prize",
       x = NULL) +
  annotate(geom = 'text', x = 56, y = 19, label = "Peace")
```

#### Add a line

Next we want a curved line with an arrow running from just underneath the text to the middle of the point. To do this, look at the data and find the relevant variables to use as a starting point. The avg_age (our x axis) for Peace is 60.8 and pct_female (y axis) is 17.1.

```{webr-r}
df |>
  ggplot(aes(x = avg_age, y = pct_female, size = n, color = category))  +
  geom_point() +
  labs(title = "Age and Gender\nat the Nobel Prize",
       x = NULL) +
  annotate(geom = 'text', x = 56, y = 19, label = "Peace") +
  annotate(geom = 'curve', x = 56, y = 18.3, xend = 60.8, yend = 17.1,
           arrow = arrow(type = 'closed', length = unit(2, 'mm')))

```

#### Drawing an arrow()

Finally we can specify an arrow with a special arrow() function. Pay attention here because the arrow syntax is a little unintuitive. We can specify an arrow type, for instance 'closed' and a length. However the length is not a simple number but a 'unit' object, where we need to put the value within the function unit() and specify a unit, such as 'mm'. You can also specify the arrow `angle` as a number between 0 and 90.

```{webr-r}

df |>
  ggplot(aes(x = avg_age, y = pct_female, size = n, color = category))  +
  geom_point() +
  labs(title = "Age and Gender\nat the Nobel Prize",
       x = NULL) +
  annotate(geom = 'text', x = 56, y = 19, label = "Peace") +
  annotate(geom = 'curve', x = 56, y = 18.3, xend = 60.8, yend = 17.1,
           arrow = arrow(type = 'closed', length = unit(2, 'mm')))

```

**Try it yourself:** Add a label, line, and arrow pointing to Physics. Run the first cell to get the relevant values as a starting point.

```{webr-r}

 df |> filter(category == "Physics")

```

Now add the text, curve, and arrow to the chart:

```{webr-r}
 df |>
  ggplot(aes(x = avg_age, y = pct_female, size = n, color = category))  +
  geom_point()
```

### other geoms with annotate()

annotate() allows us to specify any of the geoms available, but besides `text`, the most useful ones are those which we didn't use for data visualisation directly: `segment`, `rectangle`, and `curve`. You can then specify the usual aesthetics of those geoms such as colour, linetype, alpha and so forth.

#### Lines

Add a line to your plot using 'segment'. For a vertical line set the x and xend to the desired value. To draw the line the whole way across the plot set y to 0 and yend to Inf (infinite). Let's use it to mark 1969, the year the Economic Sciences prize was introduced (all the other five categories date back to 1901):

```{webr-r}

nobel_by_year |>
  ggplot(aes(x = award_year, y = n))  +
  geom_line() +
  labs(title = "Nobel Laureates Awarded per Year",
       x = NULL) +
  annotate(geom = 'segment', x = 1969, xend = 1969, y = 0, yend = Inf, linetype = 'dashed')
```

::: callout-tip
There's actually a separate layer, geom_vline(), which you can use instead.

```{webr-r}
nobel_by_year |>
  ggplot(aes(x = award_year, y = n))  +
  geom_line() +
  labs(title = "Nobel Laureates Awarded per Year",
       x = NULL) +
  geom_vline(xintercept = 1969)
```
:::

#### Rectangles

```{webr-r}
nobel_by_year |>
  ggplot(aes(x = award_year, y = n))  +
  geom_line() +
  labs(title = "Nobel Laureates Awarded per Year",
       x = NULL) +
  annotate(geom = 'rect', xmin = 1939, xmax = 1946, ymin = 0, ymax = Inf, alpha = .5, linetype = 'dashed', color = 'black')
```

Notice the dip to zero in the early 1940s? No prizes at all were awarded in 1940, 1941, or 1942, because of the Second World War.

**Try it yourself:** Create an annotated area which highlights the years from 1969 onwards, when the Economic Sciences prize has existed. Draw a label and an arrow for it. Set a colour, alpha and one other aesthetic value.

### Highlighting using colour

One effective method to draw attention to certain elements is to highlight using colours. This can be done fairly easily using our existing toolset. The set of steps are as follows:

1.  Start with your basic chart. Perhaps change colours or transparency to make the majority of the data 'fade' into the background.

2.  Next create new datasets containing only the data you wish to highlight.

3.  Add these as layers to your existing chart

4.  Change the colours of these new elements

```{webr-r}

df_highlight = df %>% filter(category %in% c('Peace', "Literature", "Economic Sciences"))

df |>
  ggplot(aes(x = avg_age, y = pct_female, size = n))  +
  geom_point(color = 'gray50', alpha = .8) +
  geom_point(data = df_highlight, color = 'red') +
  labs(title = "Age and Gender\nat the Nobel Prize",
       x = NULL) +
  annotate(geom = 'text', x = 56, y = 19, label = "Peace") +
  annotate(geom = 'curve', x = 56, y = 18.3, xend = 60.8, yend = 17.1,
           arrow = arrow(type = 'closed', length = unit(2, 'mm')))

```
