project:
  type: book
  output-dir: docs

book:
  title: "Cultural Analytics: Course Book"
  author: "Yann Ryan"
  date: "2024-09-01"
  sidebar:
    logo: images/logo.jpeg
  chapters:
    - index.qmd
    - part: "Introduction to R"
      chapters:
        - 01_r-intro.qmd
        - 02_r-basics.qmd
        - 03_r-practice.qmd
        - 04_rmarkdown.qmd
        - 05_at-home-1.qmd
    - part: "Data Analysis 1"
      chapters:
        - 06_data-analysis-1.qmd
        - 07_select.qmd
        - 08_slice.qmd
        - 09_arrange.qmd
        - 10_pipes.qmd
        - 10a_data-analysis-1-exercises.qmd
        - 11_at-home-2.qmd
    - part: "Data Analysis 2"
      chapters:
        - 12_filter.qmd
        - 13_regex.qmd
        - 14_mutate.qmd
        - 15_summarise.qmd
        - 16_grouping.qmd
        - 16a_data-analysis-2-exercises.qmd
        - 17_at-home-3.qmd
    - part: "Data Analysis 3"
      chapters:
        - 18_joins.qmd
        - 19_tidying-data.qmd
        - 20_data-challenge.qmd
        - 20a_data-analysis-3-exercises.qmd
        - 21_at-home-4.qmd
    - part: "Data Visualisation 1"
      chapters:
        - 22_data-visualisation-1.qmd
        - 23_ggplot2.qmd
        - 24_chart-types.qmd
        - 24a_data-visualisation-1-exercises.qmd
        - 25_at-home-5.qmd
    - part: "Data Visualisation 2"
      chapters:
        - 26_data-visualisation-2.qmd
        - 27_gestalt.qmd
        - 28_scales.qmd
        - 29_position-scales.qmd
        - 30_date-scales.qmd
        - 31_colour.qmd
        - 31a_data-visualisation-2-exercises.qmd
        - 32_at-home-6.qmd
    - part: "Data Visualisation 3"
      chapters:
        - 33_data-visualisation-3.qmd
        - 34_titles.qmd
        - 35_themes.qmd
        - 36_annotations.qmd
        - 36a_data-visualisation-3-exercises.qmd
    - part: "Data Visualisation 4"
      chapters:
        - 37_fair-data.qmd
        - 38_accessibility.qmd
        - 39_tidytuesday-challenge.qmd
        - 40_at-home-7.qmd
    - part: "Useful information"
      chapters:
        - 41_data-sources.qmd
    - part: "Digital Mapping 1"
      chapters:
        - 42_digital-mapping-1.qmd
   #     - digital_mapping.qmd
    #    - maps_in_r.qmd
        - 43_basemaps.qmd
        - 44_visualising-map-data.qmd
      #  - map_scales.qmd
      #  - features.qmd
        - 45_at-home-8.qmd
    - part: "Digital Mapping 2"
      chapters:
        - 46_full-map.qmd
    - part: "Digital Mapping 3"
      chapters:
        - 48_digital-mapping-3.qmd
        - 47_points-map.qmd
        - 49_interactive-maps.qmd
 #    # - part: "Advanced Chart Design and markdown reports"
 #    #   chapters: 
 #    #     - 13_design.qmd
 #    #     - 34_titles.qmd
 #    #     - 35_themes.qmd
 #    #     - 36_annotations.qmd
    - part: "Bonus: Interactivity"
      chapters:
        - 50_plotly.qmd
        - 51_tmap.qmd
  #  appendices:
 #    - extra_exercises.qmd

 #    - final_project.qmd
 #  #  - mcpherson_final_project.qmd
 # #   - Hogewoning_FinalProject.qmd
 #  #  - Polakowska-FinalProject.qmd
      


bibliography: references.bib

format:
  html:
    theme: cosmo
    number-sections: true
    number-depth: 1
    include-after-body: _includes/iframe-resize.html
  pdf:
    documentclass: scrreprt

filters: 
  - webr
webr:

  render-df: gt-interactive
editor: visual

execute:
  cache: true

  

 # packages: ['ggplot2', 'dplyr', 'stringr', 'tidyr', 'sf', 'rnaturalearth', 'rnaturalearthdata', 'usmapdata', 'plotly']